import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { customAlphabet } from "nanoid";
import { useRouter } from "next/router";

// creating a unique id
// using which alpha/ the size of the id
const nanoid = customAlphabet("abcdefghijklmnopqrstuvwxyz0123456789", 4);

const Home: NextPage = () => {
	const router = useRouter();

	function createRoom() {
		// onClick -> create room id
		// -transfer to new room page:w

		const roomId = nanoid();

		// .push move to page
		router.push(`/rooms/${roomId}`);
	}

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
				<button onClick={createRoom}>create chat room</button>
			</main>
		</>
	);
};

export default Home;
